import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../src/simulation/Simulation.js';
import {CommandSystem} from '../src/input/CommandSystem.js';
import {BuildCommand,GatherCommand,RepairCommand,SetAutoGatherCommand,isSerializableCommand} from '../src/input/Commands.js';
import {WORKER_STATE} from '../src/units/LogisticsSystem.js';

const quiet=simulation=>{simulation.ai.tick=simulation.ai.wave=1e9;return simulation;};
const advance=(simulation,seconds)=>{for(let i=0;i<Math.ceil(seconds*20);i++)simulation.step(.05);};
const engineer=simulation=>simulation.squads.find(squad=>squad.f===0&&squad.type==='engineer'&&squad.hp>0);
const valid=(simulation,type,faction=0)=>{for(let z=5;z<164;z+=2)for(let x=5;x<164;x+=2)if(!simulation.placement(faction,type,x,z))return{x,z};throw Error('no placement for '+type);};
const buildSite=(simulation,type='workshop',ids=[engineer(simulation).id])=>{const point=valid(simulation,type),error=simulation.build(0,type,point.x,point.z,ids);assert.equal(error,'');return simulation.buildings.at(-1);};

test('resource nodes are deterministic, typed and visually bounded',()=>{const a=new Simulation(),b=new Simulation();assert.equal(a.resourceNodes.length,12);assert.deepEqual(a.resourceNodes,b.resourceNodes);assert.deepEqual(new Set(a.resourceNodes.map(node=>node.type)),new Set(['supply','material','manpower']));assert.ok(a.resourceNodes.every(node=>node.amount>0&&node.r>0));});

test('gather order reaches a node, loads cargo, returns and delivers',()=>{const simulation=quiet(new Simulation()),worker=engineer(simulation),node=simulation.resourceNodes[0],before=simulation.economies[0].stock.supply;worker.x=node.x-2;worker.z=node.z;assert.equal(simulation.gather([worker.id],node.id,false),'');advance(simulation,16);assert.ok(node.amount<node.maxAmount);assert.ok(simulation.economies[0].stock.supply>before);assert.equal(worker.worker.cargo,0);assert.ok(simulation.economies[0].delivered.supply>0);});

test('depleted nodes refuse orders and preserve deterministic depletion',()=>{const simulation=quiet(new Simulation()),worker=engineer(simulation),node=simulation.resourceNodes[0];node.amount=1;worker.x=node.x;worker.z=node.z;simulation.gather([worker.id],node.id,false);advance(simulation,5);assert.equal(node.amount,0);assert.equal(node.depleted,true);assert.equal(simulation.gather([worker.id],node.id,false),'Kaynak tükenmiş');});

test('auto gather searches periodically and moves to a compatible replacement',()=>{const simulation=quiet(new Simulation()),worker=engineer(simulation),first=simulation.resourceNodes[0];first.amount=0;first.depleted=true;worker.x=39;worker.z=20;worker.worker.autoResourceType='supply';assert.equal(simulation.setAutoGather([worker.id],true,'supply'),'');advance(simulation,.1);assert.equal(worker.worker.auto,true);assert.ok([WORKER_STATE.MOVING_TO_RESOURCE,WORKER_STATE.GATHERING].includes(worker.worker.state));assert.notEqual(worker.worker.nodeId,first.id);assert.equal(simulation.resourceNodeManager.get(worker.worker.nodeId).type,'supply');});

test('New Antioch construction requires a living engineer',()=>{const simulation=quiet(new Simulation()),point=valid(simulation,'supply');assert.equal(simulation.build(0,'supply',point.x,point.z,[]),'Şantiye için muharebe mühendisi seçilmeli');assert.equal(simulation.buildings.filter(item=>item.f===0).length,3);});

test('construction remains paused without a nearby assigned engineer',()=>{const simulation=quiet(new Simulation()),site=buildSite(simulation,'workshop'),worker=engineer(simulation);worker.x=100;worker.z=100;worker.path=[];advance(simulation,2);assert.equal(site.progress,0);});

test('engineer proximity advances construction to a completed building',()=>{const simulation=quiet(new Simulation()),site=buildSite(simulation,'workshop'),worker=engineer(simulation);worker.x=site.x+site.r+1;worker.z=site.z;worker.path=[];advance(simulation,site.time+1);assert.equal(site.progress,1);assert.equal(worker.worker.state,WORKER_STATE.IDLE);assert.deepEqual(site.assignedEngineers,[]);});

test('multiple engineer assistance uses a capped diminishing-return curve',()=>{const simulation=quiet(new Simulation()),one=engineer(simulation),two=simulation.addSquad(0,'engineer',one.x+1,one.z),three=simulation.addSquad(0,'engineer',one.x+2,one.z),four=simulation.addSquad(0,'engineer',one.x+3,one.z);assert.equal(simulation.constructionSystem.constructionRate([one]),1);assert.equal(simulation.constructionSystem.constructionRate([one,two]),1.65);assert.equal(simulation.constructionSystem.constructionRate([one,two,three]),2.05);assert.equal(simulation.constructionSystem.constructionRate([one,two,three,four]),2.05);});

test('multi-resource affordability blocks construction before state mutation',()=>{const simulation=quiet(new Simulation()),worker=engineer(simulation);simulation.economies[0].stock.material=0;const count=simulation.buildings.length;assert.match(simulation.placement(0,'supply',10,82),/Yetersiz kaynak/);assert.match(simulation.build(0,'supply',10,82,[worker.id]),/Yetersiz kaynak/);assert.equal(simulation.buildings.length,count);});

test('data-driven building prerequisites unlock only after completion',()=>{const simulation=quiet(new Simulation());assert.match(simulation.placement(0,'materialDepot',10,82),/Mühendislik Atölyesi/);const workshop=simulation.addBuilding(0,'workshop',10,70,true);assert.ok(workshop.progress===1);assert.doesNotMatch(simulation.placement(0,'materialDepot',10,82),/Mühendislik Atölyesi/);});

test('workshop production queue creates five-person engineers',()=>{const simulation=quiet(new Simulation()),workshop=simulation.addBuilding(0,'workshop',10,60,true),before=simulation.count(0);assert.equal(simulation.train(workshop,'engineer'),'');assert.equal(workshop.queue.length,1);advance(simulation,16);assert.equal(workshop.queue.length,0);assert.equal(simulation.count(0),before+1);assert.equal(simulation.squads.at(-1).alive,5);});

test('force cap counts living and queued squads and rises with completed logistics',()=>{const simulation=quiet(new Simulation()),initial=simulation.forceCap(0),used=simulation.forceUsed(0),barracks=simulation.buildings.find(item=>item.f===0&&item.type==='barracks');assert.equal(initial,48);assert.equal(used,37);simulation.train(barracks,'infantry');assert.equal(simulation.forceUsed(0),45);simulation.addBuilding(0,'supply',10,60,true);simulation.economySystem.update(0);assert.equal(simulation.forceCap(0),56);});

test('repair consumes material, takes time and never exceeds max health',()=>{const simulation=quiet(new Simulation()),worker=engineer(simulation),building=simulation.buildings.find(item=>item.f===0&&item.type==='barracks');building.hp=500;building.lastHit=-100;worker.x=building.x+building.r+1;worker.z=building.z;const before=simulation.economies[0].stock.material;assert.equal(simulation.repair([worker.id],building.id),'');worker.path=[];advance(simulation,5);assert.ok(building.hp>500&&building.hp<=building.maxHp);assert.ok(simulation.economies[0].stock.material<before);});

test('repair pauses during the configured under-fire delay',()=>{const simulation=quiet(new Simulation()),worker=engineer(simulation),building=simulation.buildings.find(item=>item.f===0&&item.type==='barracks');building.hp=500;building.lastHit=simulation.time;worker.x=building.x+building.r+1;worker.z=building.z;simulation.repair([worker.id],building.id);worker.path=[];advance(simulation,2);assert.equal(building.hp,500);});

test('economy save and restore preserves stock, nodes, cargo and auto assignment',()=>{const simulation=quiet(new Simulation()),worker=engineer(simulation),node=simulation.resourceNodes[4];simulation.economies[0].stock.material=123;node.amount=77;worker.worker.cargo=12;worker.worker.cargoType='material';worker.worker.auto=true;worker.worker.autoResourceType='material';const restored=Simulation.restore(simulation.serialize()),restoredWorker=restored.squads.find(item=>item.id===worker.id);assert.equal(restored.economies[0].stock.material,123);assert.equal(restored.resourceNodeManager.get(node.id).amount,77);assert.equal(restoredWorker.worker.cargo,12);assert.equal(restoredWorker.worker.auto,true);assert.equal(restoredWorker.worker.autoResourceType,'material');});

test('save and restore preserves active construction and production progress',()=>{const simulation=quiet(new Simulation()),site=buildSite(simulation,'workshop'),worker=engineer(simulation);worker.x=site.x+site.r+1;worker.z=site.z;worker.path=[];advance(simulation,2);const barracks=simulation.buildings.find(item=>item.f===0&&item.type==='barracks');simulation.train(barracks,'infantry');advance(simulation,1);const restored=Simulation.restore(simulation.serialize()),restoredSite=restored.buildings.find(item=>item.id===site.id),restoredBarracks=restored.buildings.find(item=>item.id===barracks.id);assert.equal(restoredSite.progress,site.progress);assert.deepEqual(restoredSite.assignedEngineers,site.assignedEngineers);assert.equal(restoredBarracks.queue[0].time,barracks.queue[0].time);});

test('same seed-equivalent state, commands and ticks produce identical economy bytes',()=>{const run=()=>{const simulation=quiet(new Simulation()),commands=new CommandSystem(simulation),worker=engineer(simulation),node=simulation.resourceNodes[0];commands.dispatch(GatherCommand([worker.id],node.id,true));for(let tick=0;tick<800;tick++)simulation.step(.05);return simulation.serialize();};assert.equal(run(),run());});

test('Black Grail retains legacy income, automatic growth and its building family',()=>{const simulation=quiet(new Simulation(1)),before=simulation.resources[1];advance(simulation,1);assert.ok(simulation.resources[1]>before);simulation.resources[1]=1000;const point=valid(simulation,'tower',1);assert.equal(simulation.build(1,'tower',point.x,point.z,[]),'');const tower=simulation.buildings.at(-1);advance(simulation,tower.time+1);assert.equal(tower.progress,1);assert.equal(simulation.squads.some(item=>item.f===1&&item.type==='engineer'),false);});

test('new economy commands remain JSON-safe for replay and networking',()=>{const commands=[GatherCommand([8],'resource-1',true),RepairCommand([8],2),BuildCommand(0,'supply',20,80,[8]),SetAutoGatherCommand([8],true,'supply')];for(const command of commands){assert.equal(isSerializableCommand(command),true);assert.deepEqual(JSON.parse(JSON.stringify(command)),command);}});

test('legacy version-one saves migrate into Phase 04 economy state',()=>{const simulation=quiet(new Simulation()),legacy=JSON.parse(simulation.serialize());legacy.version=1;delete legacy.economies;delete legacy.resourceNodes;legacy.resources[0]=777;const restored=Simulation.restore(JSON.stringify(legacy));assert.equal(restored.economies[0].stock.supply,777);assert.equal(restored.resourceNodes.length,12);assert.equal(restored.serialize().includes('newAntioch'),true);});
