import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../src/simulation.js';
import {Effects,EffectPool,EFFECT_QUALITY} from '../src/effects.js';
import {VisualEvents,VFX_EVENT} from '../src/visual-events.js';
import {Renderer,Batch,INSTANCE_STRIDE} from '../src/renderer.js';
import {dynamicArt} from '../src/art.js';
import {effectArt} from '../src/effect-art.js';
const casualty={type:VFX_EVENT.CASUALTY,x:20,y:0,z:60,faction:0,yaw:.8,heavy:false};
function battle(){const s=new Simulation();s.match.state='WAR';s.squads=[];s.ai.tick=s.ai.wave=99999;s.addSquad(0,'infantry',20,60);s.addSquad(1,'infantry',30,60);return s;}
function camera(zoom=55){const r=Object.create(Renderer.prototype);r.width=1280;r.height=800;r.cam={x:30,z:60,zoom};r.vp=new Float32Array(16);r.updateCamera();return r;}
test('partial losses emit one casualty per soldier, total death is never emitted twice',()=>{const s=battle(),a=s.squads[0],b=s.squads[1],events=[];s.damage(a,b,250);s.visualEvents.drain(e=>events.push({...e}));assert.equal(events.filter(e=>e.type===VFX_EVENT.CASUALTY).length,2);s.damage(a,b,9999);s.damage(a,b,9999);s.visualEvents.drain(e=>events.push({...e}));assert.equal(events.filter(e=>e.type===VFX_EVENT.CASUALTY).length,8);assert.equal(events.filter(e=>e.type===VFX_EVENT.SQUAD_LOST).length,1);});
test('event ring is bounded even when no renderer consumes events',()=>{const q=new VisualEvents(32),identities=[...q.slots];for(let i=0;i<1000;i++)q.emit(1,i,0,0,0,0,0,0,0);assert.equal(q.count,32);assert.equal(q.dropped,968);assert.ok(q.slots.every((s,i)=>s===identities[i]));const xs=[];q.drain(e=>xs.push(e.x));assert.equal(xs[0],968);assert.equal(xs.at(-1),999);assert.equal(q.count,0);});
test('all quality levels cap every pool while recycling the same slot objects',()=>{for(let quality=0;quality<3;quality++){const fx=new Effects(quality),refs=fx.corpses.slots.slice();for(let i=0;i<500;i++){fx.event(casualty);fx.explosion(30,60,2,i%2,true);}for(const k of ['particles','smoke','corpses','marks'])assert.ok(fx[k].count()<=EFFECT_QUALITY[quality][k]);assert.ok(fx.corpses.slots.every((s,i)=>s===refs[i]));assert.ok(fx.corpses.recycled>0);}});
test('death pose progresses, corpses remain, then all short and long effects expire',()=>{const s=battle(),fx=new Effects();s.damage(s.squads[0],s.squads[1],250);fx.update(.05,s);const corpse=fx.corpses.slots[0];assert.ok(corpse.active);assert.equal(fx.corpses.count(),2);fx.update(.7,s);assert.ok(corpse.age>.68);assert.ok(corpse.active);fx.update(250,{visualEvents:new VisualEvents(),buildings:[]},{width:1,height:1,project:()=>({x:1e6,y:1e6})});for(const k of ['particles','smoke','corpses','marks'])assert.equal(fx[k].count(),0);});
test('offscreen deaths leave persistent records while expensive effects are culled',()=>{const s=battle(),fx=new Effects();s.damage(s.squads[0],s.squads[1],250);fx.update(.05,s,{width:1,height:1,project:()=>({x:1e6,y:1e6})});assert.equal(fx.corpses.count(),2);assert.equal(fx.particles.count(),0);assert.equal(fx.smoke.count(),0);assert.ok(fx.marks.count()>0);});
test('visual update and density changes never alter combat, economy or RNG decisions',()=>{const a=battle(),b=battle(),fx=new Effects();for(let i=0;i<2400;i++){a.step(.05);b.step(.05);fx.update(.05,b);if(i%120===0)fx.setQuality(i%3);}assert.equal(a.serialize(),b.serialize());});
test('saved corpse/mark ages restore without restoring live muzzle flashes',()=>{const fx=new Effects();fx.event(casualty);fx.explosion(20,60,2,0);fx.update(.5,{visualEvents:new VisualEvents(),buildings:[]});const saved=JSON.parse(JSON.stringify(fx.snapshot())),restored=new Effects();restored.restore(saved);assert.equal(restored.corpses.count(),1);assert.equal(restored.corpses.slots[0].age,.5);assert.equal(restored.marks.count(),fx.marks.count());assert.equal(restored.particles.count(),0);assert.equal(restored.smoke.count(),0);});
test('lower density immediately enforces smaller budgets without rebuilding pools',()=>{const fx=new Effects(2);for(let i=0;i<200;i++)fx.event(casualty);const ref=fx.corpses.slots;fx.setQuality(0);assert.equal(ref,fx.corpses.slots);assert.equal(fx.corpses.count(),48);assert.equal(fx.marks.count(),80);});
test('opaque and transparent instances remain finite and stride-aligned at both LODs',()=>{const sim=battle(),fx=new Effects();sim.damage(sim.squads[0],sim.squads[1],350);fx.update(.3,sim);for(const zoom of[27,100]){const r=camera(zoom),art=dynamicArt(sim,r,new Set(),null),soft=new Batch();effectArt(fx,art.batch,soft,r);for(const batch of[art.batch,soft])for(const arr of Object.values(batch.data)){assert.equal(arr.length%INSTANCE_STRIDE,0);assert.ok(arr.every(Number.isFinite));}assert.ok(soft.data.quad.length>0);assert.equal(art.batch.data.quad.length,0);}});
test('building destruction produces one collapse, and only 32 recent ruins draw',()=>{const sim=battle();sim.buildings=[];const b=sim.addBuilding(0,'tower',30,60,true);sim.damage(sim.squads[0],b,9999);sim.damage(sim.squads[0],b,9999);let n=0;sim.visualEvents.drain(e=>{if(e.type===VFX_EVENT.COLLAPSE)n++;});assert.equal(n,1);for(let i=0;i<40;i++){const v=sim.addBuilding(0,'tower',30,60,true);v.hp=0;v.diedAt=0;}sim.squads=[];const art=dynamicArt(sim,camera(),new Set(),null,null,5);assert.equal(art.visible,32);});
