// DOM/WebGL stubs exercise event wiring, not real-browser layout or GPU speed.
import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
function boot(width=393,height=852){
 const html=fs.readFileSync(new URL('../Trench-Crusade-Faz05.html',import.meta.url),'utf8');
 const elements=new Map(),storage=new Map();let frame,clock=0,draws=0;
 const context2d=new Proxy({},{get:()=>()=>{}});
 const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,drawArraysInstanced:()=>draws++},{get:(o,k)=>o[k]|| (k.toUpperCase()===k?1:()=>({}))});
 class El{constructor(id){this.id=id;this.hidden=false;this.disabled=false;this.textContent='';this.children=[];this.events={};this.style={};this.dataset={};this.classList={toggle:()=>{}};this.clientWidth=width;this.clientHeight=height;}getContext(type){return type==='2d'?context2d:gl;}addEventListener(t,f){this.events[t]=f;}append(x){this.children.push(x);}querySelector(){return this.span||=(new El('span'));}setPointerCapture(){}getBoundingClientRect(){return{left:10,top:560,width:111,height:111};}click(){this.onclick?.();}}
 for(const m of html.matchAll(/id="([^"]+)"/g))elements.set(m[1],new El(m[1]));
 const factions=[new El(),new El()];factions.forEach((x,i)=>x.dataset.faction=String(i));
 const document={getElementById:id=>elements.get(id),createElement:()=>new El(),querySelectorAll:()=>factions,addEventListener:()=>{},hidden:false};
 const window={addEventListener:()=>{}};
 const scope={document,window,devicePixelRatio:2,innerWidth:width,performance:{now:()=>clock},requestAnimationFrame:f=>frame=f,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},console,Math,Float32Array,Uint8Array,Int32Array,Set,Map};
 vm.runInNewContext(html.match(/<script>([\s\S]*)<\/script>/)[1],scope);
 const tick=()=>{clock+=50;frame(clock);};tick();return{e:id=>elements.get(id),game:window.game,tick,storage,draws:()=>draws};
}
test('standalone bundle boots, draws, starts and updates at portrait size',()=>{const app=boot();app.e('begin').click();for(let i=0;i<6;i++)app.tick();assert.equal(app.e('start').hidden,true);assert.equal(app.game.sim.count(0),5);assert.ok(app.game.sim.time>0);assert.ok(app.draws()>0);assert.match(app.e('army').textContent,/37 \/ 48/);assert.equal(Number(app.e('material').textContent),300);});
test('touch selection sends move orders; dragging pans without changing orders',()=>{const a=boot(1280,800);a.e('begin').click();const canvas=a.e('world'),s=a.game.sim.squads[0],r=a.game.renderer;const p=r.project(s.x,1,s.z);const evt=(x,y)=>({pointerId:1,clientX:x,clientY:y,button:0});canvas.events.pointerdown(evt(p.x,p.y));canvas.events.pointerup(evt(p.x,p.y));assert.equal(a.game.selected[0],s.id);const target=r.project(37,0,85);canvas.events.pointerdown(evt(target.x,target.y));canvas.events.pointerup(evt(target.x,target.y));assert.ok(s.path.length>0);const goal=JSON.stringify(s.path.at(-1)),cx=r.cam.x;canvas.events.pointerdown(evt(600,300));canvas.events.pointermove(evt(650,350));canvas.events.pointerup(evt(650,350));assert.notEqual(r.cam.x,cx);assert.equal(JSON.stringify(s.path.at(-1)),goal);});
test('build menu -> ground tap -> confirm creates an engineer-backed site and deducts three-part cost',()=>{const a=boot(1280,800);a.e('begin').click();a.e('buildMenu').click();const buttons=a.e('buildingList').children;assert.equal(buttons.length,7);buttons[1].click();assert.equal(a.game.ghost.type,'workshop');assert.equal(a.game.ghost.engineerIds.length,1);let pos;for(let z=4;z<108&&!pos;z+=2)for(let x=4;x<108;x+=2)if(!a.game.sim.placement(0,'workshop',x,z)){pos={x,z};break;}const p=a.game.renderer.project(pos.x,0,pos.z),evt={pointerId:1,clientX:p.x,clientY:p.y,button:0};a.e('world').events.pointerdown(evt);a.e('world').events.pointerup(evt);assert.equal(a.game.ghost.valid,true);a.e('confirmBuild').click();const site=a.game.sim.buildings.at(-1);assert.equal(site.type,'workshop');assert.equal(site.progress,0);assert.equal(site.assignedEngineers.length,1);assert.equal(a.game.sim.economies[0].stock.supply,345);assert.equal(a.game.sim.economies[0].stock.material,120);});
test('160-soldier performance mode preserves the saved campaign',()=>{const a=boot();a.e('begin').click();a.game.save();const saved=a.storage.get('trench-ashen-v1');a.e('stress').click();assert.equal(a.game.sim.squads.length,20);assert.equal(a.game.sim.squads.reduce((n,s)=>n+s.alive,0),160);for(let i=0;i<5;i++)a.tick();a.game.save();assert.equal(a.storage.get('trench-ashen-v1'),saved);});
test('effect density changes preserve campaign state and pool identities',()=>{const a=boot();a.e('begin').click();const state=a.game.sim.serialize(),pool=a.game.effects.particles.slots;a.e('effectQuality').click();a.e('effectQuality').click();assert.equal(a.game.effects.quality,0);assert.equal(a.game.effects.particles.limit,144);assert.equal(a.game.effects.particles.slots,pool);assert.equal(a.game.sim.serialize(),state);});
test('combat effect scenario runs through deaths without overwriting campaign',()=>{const a=boot();a.e('begin').click();a.game.save();const before=a.storage.get('trench-ashen-v1');a.e('effectStress').click();for(let i=0;i<140;i++)a.tick();assert.ok(a.game.effects.corpses.count()>0);assert.ok(a.game.effects.marks.count()>0);assert.ok(a.game.effects.particles.count()<=320);a.game.save();assert.equal(a.storage.get('trench-ashen-v1'),before);});
test('pause freezes effect lifetimes and saved corpses reload with their ages',()=>{const a=boot();a.e('begin').click();const s=a.game.sim;s.match.state='WAR';const target=s.squads.find(item=>item.f===0&&item.type==='infantry'),enemy=s.squads.find(item=>item.f===1);target.x=20;target.z=60;s.damage(enemy,target,250);a.tick();const fx=a.game.effects;assert.ok(fx.corpses.count()>0);a.e('pause').click();const age=fx.corpses.slots[0].age;for(let i=0;i<20;i++)a.tick();assert.equal(fx.corpses.slots[0].age,age);a.game.start(0,true);assert.equal(a.game.effects.corpses.slots[0].age,age);});
test('HQ result waits briefly so collapse is visible, then opens the result',()=>{const a=boot();a.e('begin').click();const s=a.game.sim;s.match.state='WAR';const hq=s.buildings.find(b=>b.id===s.match.mainObjectiveId),attacker=s.squads.find(b=>b.f===1);s.damage(attacker,hq,9999);a.tick();assert.equal(a.game.paused,false);assert.ok(a.game.effects.marks.count()>0);for(let i=0;i<40;i++)a.tick();assert.equal(a.game.paused,true);assert.equal(a.e('menuTitle').textContent,'Cephe çöktü.');});
