import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Simulation} from '../src/simulation/Simulation.js';
import {MATCH_STATE,MATCH_EVENT,validateSiegeRoles} from '../src/simulation/MatchFlow.js';
import {CommandSystem} from '../src/input/CommandSystem.js';
import {AttackCommand} from '../src/input/Commands.js';
import {formatCountdown} from '../src/ui/HUD.js';
const advance=(s,seconds)=>{for(let i=0;i<Math.ceil(seconds*20);i++)s.step(.05);};
const quiet=s=>{s.ai.tick=s.ai.wave=1e9;return s;};
test('source tree was bootstrapped and Phase 04 artifacts are archived',()=>{for(const p of ['src','data','tests','docs','Trench-Crusade-Faz04.zip'])assert.ok(fs.existsSync(new URL('../'+p,import.meta.url)));});
test('siege starts with deterministic 60 second preparation and events',()=>{const s=quiet(new Simulation());assert.equal(s.match.state,MATCH_STATE.PREPARATION);assert.equal(s.match.preparationRemaining,60);assert.equal(s.gameplayEvents[1].type,MATCH_EVENT.PREPARATION_STARTED);advance(s,50);assert.ok(Math.abs(s.match.preparationRemaining-10)<.001);advance(s,.05);assert.ok(s.gameplayEvents.some(e=>e.type===MATCH_EVENT.PREPARATION_WARNING));});
test('preparation blocks damage, attacks and enemy deployment zones',()=>{const s=quiet(new Simulation()),a=s.squads.find(x=>x.f===0),enemy=s.squads.find(x=>x.f===1),hp=enemy.hp,c=new CommandSystem(s);assert.equal(s.damage(a,enemy,100),false);assert.equal(enemy.hp,hp);assert.ok(s.move([a.id],80,40)>0);c.dispatch(AttackCommand([a.id],enemy.id,enemy.x,enemy.z));assert.equal(a.target,null);assert.equal(s.move([a.id],30,40),0);});
test('preparation transitions to war and match timer advances only in war',()=>{const s=quiet(new Simulation(0,true,{duration:5}));advance(s,59);assert.equal(s.match.matchRemaining,5);advance(s,1);assert.equal(s.match.state,MATCH_STATE.WAR);advance(s,1);assert.ok(Math.abs(s.match.matchRemaining-4)<.001);assert.ok(s.gameplayEvents.some(e=>e.type===MATCH_EVENT.WAR_STARTED));});
test('defender wins by surviving the configured duration',()=>{const s=quiet(new Simulation(0,true,{duration:.1}));advance(s,60.15);assert.equal(s.winner,0);assert.equal(s.match.state,MATCH_STATE.VICTORY);assert.equal(s.match.outcome,'DEFENDER');});
test('attacker wins by destroying the data-defined main objective',()=>{const s=quiet(new Simulation(1,true,{duration:5}));advance(s,60);const objective=s.buildings.find(b=>b.id===s.match.mainObjectiveId),attacker=s.squads.find(x=>x.f===1);s.damage(attacker,objective,99999);assert.equal(s.winner,1);assert.equal(s.match.state,MATCH_STATE.VICTORY);assert.equal(s.match.outcome,'ATTACKER');});
test('destroying a non-objective HQ does not resolve siege',()=>{const s=quiet(new Simulation());advance(s,60);const h=s.buildings.find(b=>b.f===1&&b.type==='hq'),a=s.squads.find(x=>x.f===0);s.damage(a,h,99999);assert.equal(s.winner,null);});
test('roles are data-driven and siege role validation rejects incomplete rosters',()=>{assert.equal(validateSiegeRoles(),true);assert.throws(()=>validateSiegeRoles([{gameplayRole:'DEFENDER'}]),/ATTACKER/);});
test('preparation and war saves restore timers, roles and objective state',()=>{for(const seconds of [12,62]){const s=quiet(new Simulation(0,true,{duration:9}));advance(s,seconds);const r=Simulation.restore(s.serialize());assert.deepEqual(r.match,s.match);assert.equal(r.serialize(),s.serialize());}});
test('timer and victory are deterministic for equal tick streams',()=>{const a=quiet(new Simulation(0,true,{duration:.2})),b=quiet(new Simulation(0,true,{duration:.2}));advance(a,60.25);advance(b,60.25);assert.equal(a.serialize(),b.serialize());assert.equal(a.winner,0);});
test('mobile deselect control and selection clear API are present',async()=>{const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),game=fs.readFileSync(new URL('../src/core/Game.js',import.meta.url),'utf8');assert.match(html,/id="deselect"/);assert.match(game,/\$\('deselect'\)\.onclick=.*selected\.clear/);});
test('duration choices and population/economy strategy hooks remain data-driven',()=>{const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),s=new Simulation();for(const duration of [300,600,1800,3600])assert.match(html,new RegExp(`value="${duration}"`));assert.equal(s.economies[0].strategy,'newAntioch');assert.equal(s.economies[1].strategy,'legacyBlackGrail');assert.ok(s.economies[0].population);});

test('legacy version 1/2 saves migrate into a valid fresh siege match state',()=>{for(const version of [1,2]){const s=quiet(new Simulation(0,true,{duration:300}));const data=JSON.parse(s.serialize());data.time=660;data.version=version;delete data.match;delete data.tick;delete data.gameplayEvents;if(version===1){delete data.economies;delete data.resourceNodes;}const r=Simulation.restore(JSON.stringify(data));assert.ok(r.match);assert.equal(r.match.mode,'SIEGE');assert.equal(r.match.state,'PREPARATION');assert.equal(r.match.preparationRemaining,60);assert.ok(r.match.matchRemaining>0);assert.ok(r.match.roles.includes('DEFENDER'));assert.ok(r.match.roles.includes('ATTACKER'));assert.ok(r.buildings.some(b=>b.id===r.match.mainObjectiveId&&b.f===0&&b.type==='hq'));}});

test('preparation formation goals stay inside each faction deployment zone',()=>{const s=quiet(new Simulation());for(const faction of [0,1]){const squads=s.squads.filter(x=>x.f===faction).slice(0,4),ids=squads.map(x=>x.id),zone=faction===0?{x:50,z:70}:{x:62,z:40};s.move(ids,zone.x,zone.z);for(const squad of squads){const goal=squad.path.at(-1);if(goal){if(faction===0)assert.ok(goal.x<=50);else assert.ok(goal.x>=62);}}}});

test('preparation construction footprint cannot cross faction deployment zones',()=>{const s=quiet(new Simulation());s.addBuilding(0,'supply',44,70,true);s.addBuilding(1,'supply',67,40,true);assert.match(s.placement(0,'supply',49,70),/Hazırlık bölgesi/);assert.match(s.placement(1,'supply',63,40),/Hazırlık bölgesi/);});

test('HUD countdown rounds total seconds before splitting minutes and seconds',()=>{assert.equal(formatCountdown(59.95),'01:00');assert.equal(formatCountdown(60),'01:00');assert.equal(formatCountdown(599.95),'10:00');assert.equal(formatCountdown(0),'00:00');assert.equal(formatCountdown(-1),'00:00');});

test('separation cannot push squads outside preparation deployment zones',()=>{const s=quiet(new Simulation());const defenders=s.squads.filter(x=>x.f===0).slice(0,2),attackers=s.squads.filter(x=>x.f===1).slice(0,2);for(const q of defenders){q.x=50;q.z=50;}for(const q of attackers){q.x=62;q.z=50;}s.movementSystem.separate([...defenders,...attackers],1);assert.ok(defenders.every(q=>q.x<=50));assert.ok(attackers.every(q=>q.x>=62));});
test('siege minimap source gates inactive capture markers',()=>{const source=fs.readFileSync(new URL('../src/ui/Minimap.js',import.meta.url),'utf8');assert.match(source,/match\?\.mode!=='SIEGE'.*for\(const point of sim\.points\)/s);});

test('trained squads stay inside preparation deployment zones',()=>{const s=quiet(new Simulation());const b=s.buildings.find(x=>x.f===0&&x.type==='barracks');b.x=47;b.z=70;b.queue=[{type:'infantry',time:999}];s.constructionSystem.updateProduction(b,.05);const produced=s.squads.at(-1);assert.ok(produced.f!==0||produced.x<=50);});
test('siege overlay source hides inactive capture labels',()=>{const source=fs.readFileSync(new URL('../src/ui/OverlayRenderer.js',import.meta.url),'utf8');assert.match(source,/match\?\.mode!=='SIEGE'.*sim\.points/s);});

test('legacy v1 buildings are hydrated and squads redeployed for fresh siege preparation',()=>{const s=quiet(new Simulation());const data=JSON.parse(s.serialize());data.version=1;data.time=660;delete data.match;delete data.tick;delete data.gameplayEvents;delete data.economies;delete data.resourceNodes;for(const b of data.buildings){delete b.production;delete b.storage;delete b.forceCap;}const grail=data.squads.find(q=>q.f===1);grail.x=44;const r=Simulation.restore(JSON.stringify(data));const barracks=r.buildings.find(b=>b.f===0&&b.type==='barracks'),hq=r.buildings.find(b=>b.f===0&&b.type==='hq');assert.ok(barracks.production.includes('infantry'));assert.ok(hq.forceCap>0);assert.ok(hq.storage?.supply>0);assert.ok(r.squads.filter(q=>q.f===1).every(q=>q.x>=62));assert.equal(r.match.state,'PREPARATION');});

test('engineer reassignment removes stale construction-site membership',()=>{const s=quiet(new Simulation());const engineer=s.squads.find(q=>q.f===0&&q.type==='engineer'),a=s.addBuilding(0,'supply',30,70,false),b=s.addBuilding(0,'supply',36,70,false);assert.equal(s.engineeringSystem.assist([engineer.id],a.id),'');assert.ok(a.assignedEngineers.includes(engineer.id));assert.equal(s.engineeringSystem.assist([engineer.id],b.id),'');assert.ok(!a.assignedEngineers.includes(engineer.id));assert.ok(b.assignedEngineers.includes(engineer.id));});

test('laden engineers deliver cargo before switching resource nodes',()=>{const s=quiet(new Simulation());const e=s.squads.find(q=>q.f===0&&q.type==='engineer'),nodes=s.resourceNodes.filter(n=>n.x<=50);assert.ok(nodes.length>=2);e.worker.cargo=7;e.worker.cargoType='supply';e.worker.state='RETURNING';const before=e.worker.cargo;assert.equal(s.gather([e.id],nodes[1].id,false),'');assert.equal(e.worker.cargo,before);assert.equal(e.worker.state,'RETURNING');assert.equal(e.worker.pendingNodeId,nodes[1].id);});

test('preparation rejects gather orders outside the engineer deployment zone without sticking the worker',()=>{const s=quiet(new Simulation());const e=s.squads.find(q=>q.f===0&&q.type==='engineer'),node=s.resourceNodes.find(n=>n.x>50);assert.ok(node);const result=s.gather([e.id],node.id,false);assert.match(result,/Hazırlık bölgesi/);assert.notEqual(e.worker.state,'MOVING_TO_RESOURCE');assert.equal(e.worker.nodeId,null);});

test('siege placement ignores inactive capture-point reservations',()=>{const s=quiet(new Simulation());const point=s.points[0],original=s.points;s.points=[{...point,x:34,z:70}];const result=s.placement(0,'supply',34,70);assert.doesNotMatch(result,/İkmal noktasını kapatamazsın/);s.points=original;});

test('player tap orders filter out enemy squads',()=>{const source=fs.readFileSync(new URL('../src/core/Game.js',import.meta.url),'utf8');assert.match(source,/sim\.squads\.filter\(s=>s\.f===sim\.player&&s\.hp>0&&selected\.has\(s\.id\)\)/);});

test('siege AI routes waves by siege role instead of inactive capture points',()=>{const source=fs.readFileSync(new URL('../src/ai/AIController.js',import.meta.url),'utf8');assert.match(source,/match\?\.mode==='SIEGE'/);assert.match(source,/role==='ATTACKER'.*mainObjectiveId|mainObjectiveId.*role==='ATTACKER'/s);assert.match(source,/else\{[\s\S]*sim\.points\.find/);});

test('standalone bundle footer has valid factory closure',()=>{const html=fs.readFileSync(new URL('../Trench-Crusade-Faz05.html',import.meta.url),'utf8');assert.doesNotMatch(html,/\n\}\}\};\nconst __cache/);assert.match(html,/\n\}\};\nconst __cache/);});
