import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Simulation} from '../src/simulation/Simulation.js';
import {SelectionSystem} from '../src/input/SelectionSystem.js';
import {getUnitDefinition} from '../data/units.js';
import {VISIBILITY} from '../src/world/FogOfWar.js';
import {coverAt,fieldTerrainAt,wireSpeedAt} from '../src/world/FieldDefense.js';
import {BALANCE} from '../src/core/Config.js';
import {Batch} from '../src/render/Batch.js';
import {buildingArt,dynamicArt} from '../src/render/art/BattlefieldArt.js';
import {effectArt} from '../src/render/art/EffectArt.js';
import {EffectCoordinator,PARTICLE} from '../src/effects/EffectCoordinator.js';
import {terrain} from '../src/world/Terrain.js';
import {pruneSelection,squadGroundStatus} from '../src/ui/HUD.js';
const quiet=s=>{s.ai.tick=s.ai.wave=1e9;return s;};
const advance=(s,t)=>{for(let i=0;i<Math.ceil(t/.05);i++)s.step(.05);};
const unlock=s=>{s.addBuilding(0,'workshop',33,132,true);s.economies[0].stock={supply:9999,material:9999,manpower:999};s.economySystem.update(0);return s.squads.find(q=>q.f===0&&q.type==='engineer');};
test('Tümü selects only living player combatUnit definitions',()=>{const s=quiet(new Simulation()),heavy=s.addSquad(0,'heavy',30,130),dead=s.addSquad(0,'infantry',31,130),enemy=s.squads.find(q=>q.f===1),engineer=s.squads.find(q=>q.type==='engineer');dead.hp=0;const selected=new SelectionSystem();selected.selectAll(s);assert.ok(s.squads.filter(q=>q.f===0&&q.hp>0&&getUnitDefinition(q.type).combatUnit).every(q=>selected.has(q.id)));assert.ok(selected.has(heavy.id));assert.ok(!selected.has(engineer.id));assert.ok(!selected.has(enemy.id));assert.ok(!selected.has(dead.id));});
test('siege attacker waits in PREPARATION and receives an immediate WAR assault',()=>{const s=new Simulation(0,true,{duration:300}),attackers=s.squads.filter(q=>q.f===1&&getUnitDefinition(q.type).combatUnit);s.ai.tick=s.ai.wave=1e9;s.aiController.update(.05);assert.ok(attackers.every(q=>q.target===null&&q.path.length===0));s.match.preparationRemaining=.01;s.step(.05);assert.equal(s.match.state,'WAR');assert.ok(attackers.some(q=>q.target===s.match.mainObjectiveId&&(q.path.length||q.order==='attack')));});
test('fog hides an unseen enemy and reveals it from a friendly vision source',()=>{const s=quiet(new Simulation()),enemy=s.squads.find(q=>q.f===1);assert.equal(s.fogOfWar.visible(0,enemy),false);const scout=s.squads.find(q=>q.f===0);scout.x=enemy.x;scout.z=enemy.z;s.fogOfWar.update(0,true);assert.equal(s.fogOfWar.state(0,enemy.x,enemy.z),VISIBILITY.VISIBLE);});
test('minimap applies the same fog visibility predicate to enemy units and buildings',()=>{const source=fs.readFileSync(new URL('../src/ui/Minimap.js',import.meta.url),'utf8');assert.match(source,/known\(squad,true\)/);assert.match(source,/known\(building,true\)/);assert.match(source,/VISIBILITY\.UNEXPLORED/);});
test('Observation Post provides a larger sight radius than an ordinary building',()=>{const a=quiet(new Simulation()),b=quiet(new Simulation());a.buildings=[];b.buildings=[];a.addBuilding(0,'supply',40,80,true);b.addBuilding(0,'observation',40,80,true);a.squads=[];b.squads=[];a.fogOfWar.grids[0].fill(0);b.fogOfWar.grids[0].fill(0);a.fogOfWar.update(0,true);b.fogOfWar.update(0,true);const count=s=>[...s.fogOfWar.grids[0]].filter(v=>v===VISIBILITY.VISIBLE).length;assert.ok(count(b)>count(a));assert.ok(BALANCE.fog.observationVision>BALANCE.fog.buildingVision);});
test('trench segment is a single source for terrain-style cover',()=>{const s=quiet(new Simulation()),e=unlock(s);assert.equal(s.build(0,'trench',41,123,[e.id]),'');const trench=s.buildings.at(-1);trench.progress=1;assert.equal(fieldTerrainAt(s.buildings,41,123),'trench');assert.equal(coverAt(s.buildings,41,123),getUnitDefinition('infantry')?trench.cover:0);});
test('trench placement cannot cross the preparation deployment boundary',()=>{const s=quiet(new Simulation()),e=unlock(s);assert.match(s.build(0,'trench',64,123,[e.id]),/Hazırlık bölgesi/);});
test('barbed wire applies data-driven friendly and enemy movement modifiers',()=>{const s=quiet(new Simulation()),wire=s.addBuilding(0,'barbedWire',40,90,true),friend=s.addSquad(0,'infantry',40,90),enemy=s.addSquad(1,'infantry',40,90);assert.equal(wireSpeedAt(s.buildings,friend),wire.movement.friendly);assert.equal(wireSpeedAt(s.buildings,enemy),wire.movement.enemy);assert.ok(wireSpeedAt(s.buildings,enemy)<wireSpeedAt(s.buildings,friend));});
test('terrain and renderer both consume segment data rather than fake lines',()=>{const field=fs.readFileSync(new URL('../src/world/FieldDefense.js',import.meta.url),'utf8'),art=fs.readFileSync(new URL('../src/render/art/BattlefieldArt.js',import.meta.url),'utf8');assert.match(field,/segmentLength/);assert.match(art,/v\.segmentLength/);assert.match(art,/\['trench','sandbag','barbedWire'\]/);});
test('save/load preserves Phase 05.5 fog and field defense state deterministically',()=>{const s=quiet(new Simulation()),e=unlock(s);assert.equal(s.build(0,'sandbag',41,123,[e.id],Math.PI/2),'');s.fogOfWar.update(0,true);s.fog=s.fogOfWar.snapshot();const r=Simulation.restore(s.serialize());assert.equal(r.serialize(),s.serialize());assert.equal(r.buildings.at(-1).yaw,Math.PI/2);assert.deepEqual(r.fog,s.fog);});
test('160-soldier stress state remains bounded with fog and effects enabled',()=>{const s=quiet(new Simulation());s.match.state='WAR';s.squads=[];for(let f=0;f<2;f++)for(let i=0;i<10;i++)s.addSquad(f,i%3?'infantry':'heavy',f?103:65,18+i*7);advance(s,.5);assert.equal(s.squads.reduce((n,q)=>n+q.alive,0),160);assert.ok(s.visualEvents.count<=s.visualEvents.capacity);assert.ok(s.fogOfWar.grids.every(g=>g.length===42*42));});

test('unexplored resource nodes are hidden from world render and hit testing',()=>{const s=quiet(new Simulation()),node=s.resourceNodes.find(n=>!n.depleted);s.fogOfWar.grids[s.player].fill(VISIBILITY.UNEXPLORED);const renderer={width:800,height:600,cam:{zoom:100},project:()=>({x:400,y:300})},hidden=dynamicArt(s,renderer,new Set(),null,new Batch(),0);assert.equal(hidden.batch.data.ring.length,0);s.fogOfWar.grids[s.player][s.fogOfWar.index(node.x,node.z)]=VISIBILITY.EXPLORED;const known=dynamicArt(s,renderer,new Set(),null,new Batch(),0);assert.ok(known.batch.data.ring.length>0);const gameSource=fs.readFileSync(new URL('../src/core/Game.js',import.meta.url),'utf8');assert.match(gameSource,/resource&&sim\.fogOfWar\?\.state\(sim\.player,e\.x,e\.z\)===VISIBILITY\.UNEXPLORED/);});

test('rotated field-defense art rotates component offsets with gameplay yaw',()=>{const batch=new Batch(),segment={id:999,f:0,type:'trench',x:50,z:60,hp:100,maxHp:100,progress:1,r:3,segmentLength:10,yaw:Math.PI/2};buildingArt(batch,segment,0,false);const spheres=batch.data.sphere;assert.ok(spheres.length>=15);assert.ok(Math.abs(spheres[0]-(segment.x+.8))<.01);assert.ok(Math.abs(spheres[2]-(segment.z-4))<.01);});

test('version-3 saves migrate from the legacy 112 map onto authored expanded positions',()=>{const s=quiet(new Simulation()),data=JSON.parse(s.serialize());data.version=3;delete data.fog;for(const entity of [...data.squads,...data.buildings,...data.resourceNodes]){entity.x/=1.5;entity.z/=1.5;}for(const point of data.points){point.x/=1.5;point.z/=1.5;}const hq=data.buildings.find(b=>b.f===1&&b.type==='hq');hq.x=93;hq.z=30;const node=data.resourceNodes.find(n=>n.id==='resource-8');node.x=83;node.z=19;node.amount=77;data.squads[0].path=[{x:50,z:50}];const r=Simulation.restore(JSON.stringify(data)),rhq=r.buildings.find(b=>b.id===hq.id),rn=r.resourceNodeManager.get('resource-8');assert.equal(rhq.x,139.5);assert.equal(rhq.z,45);assert.equal(rn.x,125);assert.equal(rn.z,29);assert.equal(rn.amount,77);assert.notEqual(terrain(rn.x,rn.z),'river');assert.deepEqual(r.squads[0].path,[]);});

test('rotated field defenses validate their actual segment footprint',()=>{const s=quiet(new Simulation());s.economies[0].stock={supply:9999,material:9999,manpower:999};s.addBuilding(0,'workshop',50,69,true);s.economySystem.update(0);assert.equal(s.placement(0,'trench',59,69,0),'');assert.match(s.placement(0,'trench',59,69,Math.PI/2),/siper|Geçit/i);});

test('dynamic effects disappear when their fog cell is not currently visible',()=>{const s=quiet(new Simulation()),fog=s.fogOfWar,fx=new EffectCoordinator(1),opaque=new Batch(),transparent=new Batch(),renderer={height:600,width:800,cam:{zoom:80},project:(x,y,z)=>({x:400,y:300})},x=120,z=120;fog.grids[s.player].fill(VISIBILITY.UNEXPLORED);const particle=fx.particles.take(PARTICLE.FLASH,x,.5,z,1,.5,1,0);particle.age=.1;effectArt(fx,opaque,transparent,renderer,fog,s.player);assert.equal(Object.values(opaque.data).reduce((n,a)=>n+a.length,0),0);fog.grids[s.player][fog.index(x,z)]=VISIBILITY.VISIBLE;opaque.reset();transparent.reset();effectArt(fx,opaque,transparent,renderer,fog,s.player);assert.ok(Object.values(opaque.data).reduce((n,a)=>n+a.length,0)>0);});

test('selected enemies are dropped when they leave current vision',()=>{const s=quiet(new Simulation()),enemy=s.squads.find(q=>q.f!==s.player),selected=new Set([enemy.id]);s.fogOfWar.grids[s.player].fill(VISIBILITY.UNEXPLORED);pruneSelection(s,selected);assert.equal(selected.has(enemy.id),false);s.fogOfWar.grids[s.player][s.fogOfWar.index(enemy.x,enemy.z)]=VISIBILITY.VISIBLE;selected.add(enemy.id);pruneSelection(s,selected);assert.equal(selected.has(enemy.id),true);});

test('armed defenses reveal at least their full weapon range',()=>{const s=quiet(new Simulation());s.squads=[];s.buildings=[];const tower=s.addBuilding(1,'tower',80,80,true);s.fogOfWar.grids[1].fill(VISIBILITY.UNEXPLORED);s.fogOfWar.update(0,true);assert.ok(BALANCE.fog.armedBuildingVision>=BALANCE.tower.range);assert.equal(s.fogOfWar.state(1,tower.x+BALANCE.tower.range,tower.z),VISIBILITY.VISIBLE);});

test('HUD ground status reports constructed sandbag cover',()=>{const s=quiet(new Simulation()),sandbag=s.addBuilding(0,'sandbag',40,90,true),squad=s.addSquad(0,'infantry',40,90);sandbag.progress=1;assert.equal(coverAt(s.buildings,squad.x,squad.z),sandbag.cover);assert.match(squadGroundStatus(s,squad),/Saha savunması: %24 koruma/);assert.doesNotMatch(squadGroundStatus(s,squad),/Açık arazi/);});

test('version-3 preparation migration keeps both factions inside new deployment zones',()=>{const s=quiet(new Simulation()),data=JSON.parse(s.serialize());data.version=3;delete data.fog;const aSquad=data.squads.find(q=>q.f===0),gSquad=data.squads.find(q=>q.f===1),aBuilding=data.buildings.find(b=>b.f===0&&b.type==='supply'),gBuilding=data.buildings.find(b=>b.f===1&&b.type==='supply');aSquad.x=50;gSquad.x=62;aBuilding.x=50;gBuilding.x=62;for(const entity of [...data.squads,...data.buildings,...data.resourceNodes]){if(entity!==aSquad&&entity!==gSquad&&entity!==aBuilding&&entity!==gBuilding){entity.x/=1.5;entity.z/=1.5;}}const r=Simulation.restore(JSON.stringify(data));const ra=r.squads.find(q=>q.id===aSquad.id),rg=r.squads.find(q=>q.id===gSquad.id),rab=r.buildings.find(b=>b.id===aBuilding.id),rgb=r.buildings.find(b=>b.id===gBuilding.id);assert.ok(ra.x<=65);assert.ok(rg.x>=103);assert.ok(rab.x+(rab.footprint||rab.r)<=65);assert.ok(rgb.x-(rgb.footprint||rgb.r)>=103);});
