import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Simulation} from '../src/simulation/Simulation.js';
import {SelectionSystem} from '../src/input/SelectionSystem.js';
import {getUnitDefinition} from '../data/units.js';
import {VISIBILITY} from '../src/world/FogOfWar.js';
import {coverAt,fieldTerrainAt,wireSpeedAt} from '../src/world/FieldDefense.js';
import {BALANCE} from '../src/core/Config.js';
import {Batch} from '../src/render/Batch.js';
import {buildingArt,dynamicArt} from '../src/render/art/BattlefieldArt.js';
const quiet=s=>{s.ai.tick=s.ai.wave=1e9;return s;};
const advance=(s,t)=>{for(let i=0;i<Math.ceil(t/.05);i++)s.step(.05);};
const unlock=s=>{s.addBuilding(0,'workshop',33,132,true);s.economies[0].stock={supply:9999,material:9999,manpower:999};s.economySystem.update(0);return s.squads.find(q=>q.f===0&&q.type==='engineer');};
test('Tümü selects only living player combatUnit definitions',()=>{const s=quiet(new Simulation()),heavy=s.addSquad(0,'heavy',30,130),dead=s.addSquad(0,'infantry',31,130),enemy=s.squads.find(q=>q.f===1),engineer=s.squads.find(q=>q.type==='engineer');dead.hp=0;const selected=new SelectionSystem();selected.selectAll(s);assert.ok(s.squads.filter(q=>q.f===0&&q.hp>0&&getUnitDefinition(q.type).combatUnit).every(q=>selected.has(q.id)));assert.ok(selected.has(heavy.id));assert.ok(!selected.has(engineer.id));assert.ok(!selected.has(enemy.id));assert.ok(!selected.has(dead.id));});
test('siege attacker waits in PREPARATION and receives an immediate WAR assault',()=>{const s=new Simulation(0,true,{duration:300}),attackers=s.squads.filter(q=>q.f===1&&getUnitDefinition(q.type).combatUnit);s.ai.tick=s.ai.wave=1e9;s.aiController.update(.05);assert.ok(attackers.every(q=>q.target===null&&q.path.length===0));s.match.preparationRemaining=.01;s.step(.05);assert.equal(s.match.state,'WAR');assert.ok(attackers.some(q=>q.target===s.match.mainObjectiveId&&(q.path.length||q.order==='attack')));});
test('fog hides an unseen enemy and reveals it from a friendly vision source',()=>{const s=quiet(new Simulation()),enemy=s.squads.find(q=>q.f===1);assert.equal(s.fogOfWar.visible(0,enemy),false);const scout=s.squads.find(q=>q.f===0);scout.x=enemy.x;scout.z=enemy.z;s.fogOfWar.update(0,true);assert.equal(s.fogOfWar.state(0,enemy.x,enemy.z),VISIBILITY.VISIBLE);});
test('minimap applies the same fog visibility predicate to enemy units and buildings',()=>{const source=fs.readFileSync(new URL('../src/ui/Minimap.js',import.meta.url),'utf8');assert.match(source,/known\(squad,true\)/);assert.match(source,/known\(building,true\)/);assert.match(source,/VISIBILITY\.UNEXPLORED/);});
test('Observation Post provides a larger sight radius than an ordinary building',()=>{const a=quiet(new Simulation()),b=quiet(new Simulation());a.buildings=[];b.buildings=[];a.addBuilding(0,'supply',40,80,true);b.addBuilding(0,'observation',40,80,true);a.squads=[];b.squads=[];a.fogOfWar.grids[0].fill(0);b.fogOfWar.grids[0].fill(0);a.fogOfWar.update(0,true);b.fogOfWar.update(0,true);const count=s=>[...s.fogOfWar.grids[0]].filter(v=>v===VISIBILITY.VISIBLE).length;assert.ok(count(b)>count(a));assert.ok(BALANCE.fog.observationVision>BALANCE.fog.buildingVision);});
test('trench segment is a single source for terrain-style cover',()=>{const s=quiet(new Simulation()),e=unlock(s);assert.equal(s.build(0,'trench',41,123,[e.id]),'');const trench=s.buildings.at(-1);trench.progress=1;assert.equal(fieldTerrainAt(s.buildings,41,123),'trench');assert.equal(coverAt(s.buildings,41,123),getUnitDefinition('infantry')?trench.cover:0);});
test('trench placement cannot cross the preparation deployment boundary',()=>{const s=quiet(new Simulation()),e=unlock(s);assert.match(s.build(0,'trench',64,123,[e.id]),/Hazırlık bölgesi/);});
test('barbed wire applies data-driven friendly and enemy movement modifiers',()=>{const s=quiet(new Simulation()),wire=s.addBuilding(0,'barbedWire',40,90,true),friend=s.addSquad(0,'infantry',40,90),enemy=s.addSquad(1,'infantry',40,90);assert.equal(wireSpeedAt(s.buildings,friend),wire.movement.friendly);assert.equal(wireSpeedAt(s.buildings,enemy),wire.movement.enemy);assert.ok(wireSpeedAt(s.buildings,enemy)<wireSpeedAt(s.buildings,friend));});
test('terrain and renderer both consume segment data rather than fake lines',()=>{const field=fs.readFileSync(new URL('../src/world/FieldDefense.js',import.meta.url),'utf8'),art=fs.readFileSync(new URL('../src/render/art/BattlefieldArt.js',import.meta.url),'utf8');assert.match(field,/segmentLength/);assert.match(art,/v\.segmentLength/);assert.match(art,/\['trench','sandbag','barbedWire'\]/);});
test('save/load preserves Phase 05.5 fog and field defense state deterministically',()=>{const s=quiet(new Simulation()),e=unlock(s);assert.equal(s.build(0,'sandbag',41,123,[e.id],Math.PI/2),'');s.fogOfWar.update(0,true);s.fog=s.fogOfWar.snapshot();const r=Simulation.restore(s.serialize());assert.equal(r.serialize(),s.serialize());assert.equal(r.buildings.at(-1).yaw,Math.PI/2);assert.deepEqual(r.fog,s.fog);});
test('160-soldier stress state remains bounded with fog and effects enabled',()=>{const s=quiet(new Simulation());s.match.state='WAR';s.squads=[];for(let f=0;f<2;f++)for(let i=0;i<10;i++)s.addSquad(f,i%3?'infantry':'heavy',f?103:65,18+i*7);advance(s,.5);assert.equal(s.squads.reduce((n,q)=>n+q.alive,0),160);assert.ok(s.visualEvents.count<=s.visualEvents.capacity);assert.ok(s.fogOfWar.grids.every(g=>g.length===42*42));});

test('unexplored resource nodes are hidden from world render and hit testing',()=>{const s=quiet(new Simulation()),node=s.resourceNodes.find(n=>!n.depleted);s.fogOfWar.grids[s.player].fill(VISIBILITY.UNEXPLORED);const renderer={width:800,height:600,cam:{zoom:100},project:()=>({x:400,y:300})},hidden=dynamicArt(s,renderer,new Set(),null,new Batch(),0);assert.equal(hidden.batch.data.ring.length,0);s.fogOfWar.grids[s.player][s.fogOfWar.index(node.x,node.z)]=VISIBILITY.EXPLORED;const known=dynamicArt(s,renderer,new Set(),null,new Batch(),0);assert.ok(known.batch.data.ring.length>0);const gameSource=fs.readFileSync(new URL('../src/core/Game.js',import.meta.url),'utf8');assert.match(gameSource,/resource&&sim\.fogOfWar\?\.state\(sim\.player,e\.x,e\.z\)===VISIBILITY\.UNEXPLORED/);});

test('rotated field-defense art rotates component offsets with gameplay yaw',()=>{const batch=new Batch(),segment={id:999,f:0,type:'trench',x:50,z:60,hp:100,maxHp:100,progress:1,r:3,segmentLength:10,yaw:Math.PI/2};buildingArt(batch,segment,0,false);const spheres=batch.data.sphere;assert.ok(spheres.length>=15);assert.ok(Math.abs(spheres[0]-(segment.x+.8))<.01);assert.ok(Math.abs(spheres[2]-(segment.z-4))<.01);});
