export class OverlayRenderer {
  constructor(context){this.context=context;}
  draw(sim,renderer,selected,drag,orderMarker,now=performance.now()){
    const context=this.context;context.clearRect(0,0,renderer.width,renderer.height);
    for(const entity of [...sim.squads,...sim.buildings]){if(entity.hp<=0)continue;if(!selected.has(entity.id)&&entity.hp===entity.maxHp&&!(entity.progress<1)&&!entity.path)continue;const point=renderer.project(entity.x,entity.path?2.4:7,entity.z);if(point.x<0||point.x>renderer.width||point.y<0||point.y>renderer.height)continue;const width=entity.path?27:45;context.fillStyle='#0c1412df';context.fillRect(point.x-width/2-1,point.y-1,width+2,5);context.fillStyle=entity.f===sim.player?'#bed095':'#cb7960';context.fillRect(point.x-width/2,point.y,width*entity.hp/entity.maxHp,3);if(entity.progress<1){context.fillStyle='#cdb078';context.fillRect(point.x-width/2,point.y+5,width*entity.progress,2);}if(selected.has(entity.id)&&entity.path?.length){context.strokeStyle='#d6c98c66';context.setLineDash([4,5]);context.beginPath();const origin=renderer.project(entity.x,.3,entity.z);context.moveTo(origin.x,origin.y);for(const waypoint of entity.path){const projected=renderer.project(waypoint.x,.3,waypoint.z);context.lineTo(projected.x,projected.y);}context.stroke();context.setLineDash([]);}}
    if(sim.match?.mode!=='SIEGE')for(const [point,index] of sim.points.map((point,index)=>[point,index])){const projected=renderer.project(point.x,4,point.z);context.font='10px Arial';context.textAlign='center';context.fillStyle='#e0d4ab';context.fillText(['I · KUZEY','II · MERKEZ','III · GÜNEY'][index],projected.x,projected.y);}
    if(drag?.select&&drag.moved){context.fillStyle='#c9ca7420';context.strokeStyle='#d0c58c';context.fillRect(drag.x,drag.y,drag.cx-drag.x,drag.cy-drag.y);context.strokeRect(drag.x,drag.y,drag.cx-drag.x,drag.cy-drag.y);}
    if(orderMarker){const age=(now-orderMarker.t)/1000;if(age>1)return null;const point=renderer.project(orderMarker.x,.3,orderMarker.z);context.strokeStyle=orderMarker.attack?'#e89a6f':'#e5d397';if(orderMarker.attack){context.beginPath();context.moveTo(point.x-15,point.y-8);context.lineTo(point.x+15,point.y+8);context.moveTo(point.x+15,point.y-8);context.lineTo(point.x-15,point.y+8);context.stroke();}context.beginPath();context.ellipse(point.x,point.y,12+age*14,6+age*7,0,0,7);context.stroke();}
    return orderMarker;
  }
}
