import {BALANCE} from '../core/Config.js';
import {dist} from '../core/math.js';
import {WORKER_STATE} from './LogisticsSystem.js';
import {VFX_EVENT} from '../effects/VisualEvents.js';
export class EngineeringSystem {
  constructor(simulation,movementSystem){Object.assign(this,{simulation,movementSystem});}
  engineers(ids,faction=null){return this.simulation.squads.filter(squad=>ids.includes(squad.id)&&(faction===null||squad.f===faction)&&squad.type==='engineer'&&squad.hp>0);}
  approach(squad,building){const angle=Math.atan2(squad.z-building.z,squad.x-building.x),radius=building.r+2;return{x:building.x+Math.cos(angle)*radius,z:building.z+Math.sin(angle)*radius};}
  detach(squad){const previous=this.simulation.buildings.find(item=>item.id===squad.worker?.targetBuildingId);if(previous?.assignedEngineers)previous.assignedEngineers=previous.assignedEngineers.filter(id=>id!==squad.id);}
  deferForCargo(squad,building,state){const worker=squad.worker;if(!(worker.cargo>0))return false;const logistics=this.simulation.logisticsSystem,depot=logistics.depot(squad,worker.cargoType);if(!depot)return null;this.detach(squad);worker.auto=false;worker.pendingNodeId=null;worker.pendingEngineering={state,buildingId:building.id};worker.targetBuildingId=null;worker.nodeId=null;worker.depotId=depot.id;worker.state=WORKER_STATE.RETURNING;worker.timer=0;logistics.moveToDepot(squad,depot);return true;}
  resumePending(squad){const pending=squad.worker?.pendingEngineering;if(!pending)return false;squad.worker.pendingEngineering=null;return pending.state===WORKER_STATE.REPAIRING?this.repair([squad.id],pending.buildingId):this.assist([squad.id],pending.buildingId);}
  assist(ids,buildingId){const building=this.simulation.buildings.find(item=>item.id===buildingId&&item.hp>0&&item.progress<1);if(!building)return 'Aktif şantiye bulunamadı';const engineers=this.engineers(ids,building.f);if(!engineers.length)return 'Muharebe mühendisi seçilmeli';if(engineers.some(squad=>squad.worker.cargo>0&&!this.simulation.logisticsSystem.depot(squad,squad.worker.cargoType)))return 'Yük teslim edilecek depo yok';for(const squad of engineers){const deferred=this.deferForCargo(squad,building,WORKER_STATE.CONSTRUCTING);if(deferred)continue;this.detach(squad);squad.worker.auto=false;squad.worker.pendingEngineering=null;if(!building.assignedEngineers.includes(squad.id))building.assignedEngineers.push(squad.id);squad.worker.state=WORKER_STATE.CONSTRUCTING;squad.worker.targetBuildingId=building.id;squad.worker.nodeId=null;const goal=this.approach(squad,building);this.movementSystem.move([squad.id],goal.x,goal.z);}return '';}
  repair(ids,buildingId){const building=this.simulation.buildings.find(item=>item.id===buildingId&&item.hp>0&&item.progress===1);if(!building)return 'Tamir edilecek yapı bulunamadı';if(building.hp>=building.maxHp)return 'Yapı zaten sağlam';const engineers=this.engineers(ids,building.f);if(!engineers.length)return 'Muharebe mühendisi seçilmeli';if(engineers.some(squad=>squad.worker.cargo>0&&!this.simulation.logisticsSystem.depot(squad,squad.worker.cargoType)))return 'Yük teslim edilecek depo yok';for(const squad of engineers){const deferred=this.deferForCargo(squad,building,WORKER_STATE.REPAIRING);if(deferred)continue;this.detach(squad);squad.worker.auto=false;squad.worker.pendingEngineering=null;squad.worker.state=WORKER_STATE.REPAIRING;squad.worker.targetBuildingId=building.id;squad.worker.nodeId=null;const goal=this.approach(squad,building);this.movementSystem.move([squad.id],goal.x,goal.z);}return '';}
  stop(ids){for(const squad of this.engineers(ids)){const worker=squad.worker,building=this.simulation.buildings.find(item=>item.id===worker.targetBuildingId);if(building?.assignedEngineers)building.assignedEngineers=building.assignedEngineers.filter(id=>id!==squad.id);worker.state=WORKER_STATE.IDLE;worker.targetBuildingId=null;worker.nodeId=null;worker.timer=0;}}
  update(dt){for(const squad of this.simulation.squads){if(squad.hp<=0||squad.type!=='engineer'||squad.worker?.state!==WORKER_STATE.REPAIRING)continue;const worker=squad.worker,building=this.simulation.buildings.find(item=>item.id===worker.targetBuildingId&&item.hp>0&&item.progress===1);if(!building||building.hp>=building.maxHp){worker.state=WORKER_STATE.IDLE;worker.targetBuildingId=null;continue;}if(dist(squad,building)>building.r+BALANCE.repair.radius)continue;if(this.simulation.time-(building.lastHit??-100)<BALANCE.repair.combatDelay)continue;const economy=this.simulation.economySystem.get(squad.f),hp=Math.min(BALANCE.repair.rate*dt,building.maxHp-building.hp),cost={material:hp*BALANCE.repair.materialPerHp};if(!economy.charge(cost))continue;building.hp+=hp;squad.path=[];worker.effectCooldown-=dt;if(worker.effectCooldown<=0){this.simulation.visualEvents.emit(VFX_EVENT.REPAIR,squad.x,.6,squad.z,building.x,1,building.z,squad.f,squad.f,1,.7,squad.yaw,false,true,building.id);worker.effectCooldown=BALANCE.repair.effectPeriod;}}}
}
