import {BALANCE} from '../core/Config.js';
import {dist} from '../core/math.js';
import {getResourceDefinition} from '../../data/resources.js';
import {VFX_EVENT} from '../effects/VisualEvents.js';
import {FACTION_DEFINITIONS} from '../../data/factions.js';

export const WORKER_STATE=Object.freeze({IDLE:'IDLE',MOVING_TO_RESOURCE:'MOVING_TO_RESOURCE',GATHERING:'GATHERING',RETURNING:'RETURNING',DELIVERING:'DELIVERING',CONSTRUCTING:'CONSTRUCTING',REPAIRING:'REPAIRING'});

export class LogisticsSystem {
  constructor(simulation,nodeManager,movementSystem){Object.assign(this,{simulation,nodeManager,movementSystem});}
  engineers(ids,faction=null){return this.simulation.squads.filter(squad=>ids.includes(squad.id)&&(faction===null||squad.f===faction)&&squad.type==='engineer'&&squad.hp>0);}
  reset(worker){worker.state=WORKER_STATE.IDLE;worker.nodeId=null;worker.targetBuildingId=null;worker.depotId=null;worker.pendingNodeId=null;worker.timer=0;}
  inPreparationZone(squad,node){if(this.simulation.match?.state!=='PREPARATION')return true;const zone=FACTION_DEFINITIONS[squad.f]?.deploymentZone;return !zone||node.x>=zone.minX&&node.x<=zone.maxX;}
  detachConstruction(squad){const previous=this.simulation.buildings.find(item=>item.id===squad.worker?.targetBuildingId);if(previous?.assignedEngineers)previous.assignedEngineers=previous.assignedEngineers.filter(id=>id!==squad.id);}
  beginGather(squad,node,auto=false){if(!this.inPreparationZone(squad,node))return false;const worker=squad.worker;this.detachConstruction(squad);worker.state=WORKER_STATE.MOVING_TO_RESOURCE;worker.nodeId=node.id;worker.targetBuildingId=null;worker.auto=auto||worker.auto;worker.autoResourceType=node.type;worker.timer=0;const failed=this.movementSystem.move([squad.id],node.x,node.z);if(failed){const keepAuto=worker.auto,resourceType=worker.autoResourceType;this.reset(worker);worker.auto=keepAuto;worker.autoResourceType=resourceType;return false;}return true;}
  gather(ids,nodeId,auto=false){const node=this.nodeManager.get(nodeId);if(!node||node.depleted)return 'Kaynak tükenmiş';const engineers=this.engineers(ids);if(!engineers.length)return 'Muharebe mühendisi seçilmeli';if(engineers.some(squad=>!this.inPreparationZone(squad,node)))return 'Hazırlık bölgesi dışındaki kaynağa erişilemez';if(engineers.some(squad=>squad.worker.cargo>0&&!this.depot(squad,squad.worker.cargoType)))return 'Yük teslim edilecek depo yok';let failed=false;for(const squad of engineers){const worker=squad.worker;this.detachConstruction(squad);worker.auto=auto||worker.auto;worker.autoResourceType=node.type;if(worker.cargo>0){const depot=this.depot(squad,worker.cargoType);worker.pendingNodeId=node.id;worker.targetBuildingId=null;worker.depotId=depot.id;worker.state=WORKER_STATE.RETURNING;worker.timer=0;this.moveToDepot(squad,depot);continue;}if(!this.beginGather(squad,node,auto))failed=true;}return failed?'Kaynağa erişilemiyor':'';}
  interrupt(ids){for(const squad of this.engineers(ids)){const worker=squad.worker,cargo=worker.cargo,cargoType=worker.cargoType;this.detachConstruction(squad);this.reset(worker);worker.auto=false;worker.cargo=cargo;worker.cargoType=cargoType;}}
  setAuto(ids,enabled,resourceType=null){const engineers=this.engineers(ids);if(!engineers.length)return 'Muharebe mühendisi seçilmeli';for(const squad of engineers){squad.worker.auto=enabled;squad.worker.autoResourceType=resourceType||squad.worker.autoResourceType;squad.worker.searchCooldown=0;if(enabled&&squad.worker.state===WORKER_STATE.IDLE)this.findNext(squad);}return '';}
  stop(ids){for(const squad of this.engineers(ids)){const worker=squad.worker;worker.auto=false;worker.pendingNodeId=null;if(worker.cargo>0){const depot=this.depot(squad,worker.cargoType);if(depot){worker.depotId=depot.id;worker.state=WORKER_STATE.RETURNING;this.moveToDepot(squad,depot);continue;}}this.reset(worker);}}
  findNext(squad){const worker=squad.worker;worker.searchCooldown=BALANCE.logistics.autoSearchPeriod;let node=this.nodeManager.nearest(squad,worker.autoResourceType);if(node&&!this.inPreparationZone(squad,node)){let best=null,bestDistance=Infinity;for(const candidate of this.simulation.resourceNodes){if(candidate.depleted||candidate.amount<=0||worker.autoResourceType&&candidate.type!==worker.autoResourceType||!this.inPreparationZone(squad,candidate))continue;const distance=dist(squad,candidate);if(distance<bestDistance){best=candidate;bestDistance=distance;}}node=best;}if(!node){this.reset(worker);worker.auto=true;return false;}return this.beginGather(squad,node,true);}
  depot(squad,type){let best=null,bestDistance=Infinity;for(const building of this.simulation.buildings){if(building.f!==squad.f||building.hp<=0||building.progress<1||!['hq','supply','materialDepot'].includes(building.type))continue;if(type==='material'&&!['hq','materialDepot'].includes(building.type))continue;const distance=dist(squad,building);if(distance<bestDistance){best=building;bestDistance=distance;}}return best;}
  moveToDepot(squad,depot){const angle=Math.atan2(squad.z-depot.z,squad.x-depot.x),radius=depot.r+2;this.movementSystem.move([squad.id],depot.x+Math.cos(angle)*radius,depot.z+Math.sin(angle)*radius);}
  update(dt){
    for(const squad of this.simulation.squads){if(squad.hp<=0||squad.type!=='engineer'||!squad.worker)continue;const worker=squad.worker;worker.effectCooldown=Math.max(0,worker.effectCooldown-dt);
      if(worker.state===WORKER_STATE.IDLE){if(worker.auto){worker.searchCooldown-=dt;if(worker.searchCooldown<=0)this.findNext(squad);}continue;}
      if(worker.state===WORKER_STATE.MOVING_TO_RESOURCE){const node=this.nodeManager.get(worker.nodeId);if(!node||node.depleted){this.reset(worker);if(worker.auto)this.findNext(squad);continue;}if(dist(squad,node)<=BALANCE.logistics.arrivalRadius){squad.path=[];squad.order='hold';worker.state=WORKER_STATE.GATHERING;worker.timer=0;}continue;}
      if(worker.state===WORKER_STATE.GATHERING){const node=this.nodeManager.get(worker.nodeId);if(!node||node.depleted||dist(squad,node)>BALANCE.logistics.arrivalRadius){const keepAuto=worker.auto,resourceType=worker.autoResourceType,cargo=worker.cargo,cargoType=worker.cargoType;this.reset(worker);worker.auto=keepAuto;worker.autoResourceType=resourceType;worker.cargo=cargo;worker.cargoType=cargoType;if(worker.auto)this.findNext(squad);continue;}worker.timer+=dt;const definition=getResourceDefinition(node.type);if(worker.effectCooldown<=0){this.simulation.visualEvents.emit(VFX_EVENT.WORK,squad.x,.4,squad.z,node.x,.2,node.z,squad.f,squad.f,1,.6,squad.yaw,false,false,squad.id);worker.effectCooldown=.7;}if(worker.timer>=definition.gatherTime){worker.cargoType=node.type;worker.cargo=this.nodeManager.take(node,definition.cargo);worker.timer=0;const depot=this.depot(squad,node.type);if(!depot){this.reset(worker);continue;}worker.depotId=depot.id;worker.state=WORKER_STATE.RETURNING;this.moveToDepot(squad,depot);}continue;}
      if(worker.state===WORKER_STATE.RETURNING){const depot=this.simulation.buildings.find(building=>building.id===worker.depotId&&building.hp>0&&building.progress===1);if(!depot){const replacement=this.depot(squad,worker.cargoType);if(!replacement){this.reset(worker);continue;}worker.depotId=replacement.id;this.moveToDepot(squad,replacement);continue;}if(dist(squad,depot)<=depot.r+BALANCE.logistics.deliveryRadius){squad.path=[];worker.state=WORKER_STATE.DELIVERING;worker.timer=0;}continue;}
      if(worker.state===WORKER_STATE.DELIVERING){worker.timer+=dt;if(worker.timer>=.35){const economy=this.simulation.economySystem.get(squad.f),accepted=economy.credit(worker.cargoType,worker.cargo);worker.cargo-=accepted;if(accepted>0)this.simulation.visualEvents.emit(VFX_EVENT.DELIVERY,squad.x,.3,squad.z,0,0,0,squad.f,squad.f,1,.5,squad.yaw,false,false,squad.id);if(worker.cargo<=0){const pendingNodeId=worker.pendingNodeId,keepAuto=worker.auto;worker.cargo=0;worker.cargoType=null;this.reset(worker);worker.auto=keepAuto;if(pendingNodeId){const pending=this.nodeManager.get(pendingNodeId);if(pending&&!pending.depleted&&this.beginGather(squad,pending,keepAuto))continue;}if(worker.auto)this.findNext(squad);}else worker.timer=0;}continue;}
    }
  }
}
